<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="insurance_process" nsURI="insurance_process" nsPrefix="insurance_process">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eAnnotations source="om=insurance_meta_process"/>
    <eAnnotations source="lm">
      <details key="no.hvl.multecore.examples.bicycle2019.supp.languages" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__metamodels" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__supplementaries" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="__contains" upperBound="-1"
        eType="#//EClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__relationNames" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__potency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__parentNodes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__isAbstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__attributeNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__supplementaryNodes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference" upperBound="-1"
        eType="#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManagerRole" eSuperTypes="#//EClass">
    <eAnnotations source="type=Role@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executes" upperBound="-1"
        eType="#//ReviewClaimTask">
      <eAnnotations source="type=executes@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimArtifact" eSuperTypes="#//EClass">
    <eAnnotations source="type=IArtifact"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenBoss" eSuperTypes="#//EClass">
    <eAnnotations source="type=Actor@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creates" upperBound="-1"
        eType="#//AssessClaimTask">
      <eAnnotations source="type=creates@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimHandlingManagerRole" eSuperTypes="#//EClass">
    <eAnnotations source="type=Role@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executes" upperBound="-1"
        eType="#//AuthorizePaymentTask">
      <eAnnotations source="type=executes@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimHandling" eSuperTypes="#//EClass">
    <eAnnotations source="type=Process@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c_ac" upperBound="-1" eType="#//AssessClaimTask">
      <eAnnotations source="type=contains@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c_rc" upperBound="-1" eType="#//ReceiveClaimTask">
      <eAnnotations source="type=contains@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c_ap" upperBound="-1" eType="#//AuthorizePaymentTask">
      <eAnnotations source="type=contains@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c_pp" upperBound="-1" eType="#//PayPremiumTask">
      <eAnnotations source="type=contains@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PayPremiumTask" eSuperTypes="#//EClass">
    <eAnnotations source="type=Task@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimPaymentDecisionArtifact" eSuperTypes="#//EClass">
    <eAnnotations source="type=IArtifact"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveClaimTask" eSuperTypes="#//EClass">
    <eAnnotations source="type=Task@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeniorManagerRole" eSuperTypes="#//ManagerRole">
    <eAnnotations source="type=SeniorRole@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinancialOfficerRole" eSuperTypes="#//EClass">
    <eAnnotations source="type=Role@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executes" upperBound="-1"
        eType="#//AuthorizePaymentTask">
      <eAnnotations source="type=executes@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthorizePaymentTask" eSuperTypes="#//EClass">
    <eAnnotations source="type=Task@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectLeaderRole" eSuperTypes="#//EClass">
    <eAnnotations source="type=Role@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssessClaimTask" eSuperTypes="#//EClass">
    <eAnnotations source="type=Task@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produces" upperBound="-1"
        eType="#//ClaimPaymentDecisionArtifact">
      <eAnnotations source="type=produces@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" upperBound="-1" eType="#//ClaimArtifact">
      <eAnnotations source="type=uses@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReviewClaimTask" eSuperTypes="#//EClass">
    <eAnnotations source="type=Task@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
</ecore:EPackage>
