<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="insurance_process_conf" nsURI="insurance_process_conf" nsPrefix="insurance_process_conf">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eAnnotations source="om=insurance_process"/>
    <eAnnotations source="lm">
      <details key="no.hvl.multecore.examples.bicycle2019.supp.languages" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__metamodels" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__supplementaries" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="__contains" upperBound="-1"
        eType="#//EClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__relationNames" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__potency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__parentNodes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__isAbstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__attributeNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__supplementaryNodes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference" upperBound="-1"
        eType="#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JohnSmith" eSuperTypes="#//EClass">
    <eAnnotations source="type=Actor@3"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSM" upperBound="-1" eType="#//SeniorManager">
      <eAnnotations source="type=hasRole@3"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performs" upperBound="-1"
        eType="#//ReviewingClaim123">
      <eAnnotations source="type=performs@3"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPL" upperBound="-1" eType="#//ProjectLeader">
      <eAnnotations source="type=hasRole@3"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReviewingClaim123" eSuperTypes="#//EClass">
    <eAnnotations source="type=ReviewClaimTask"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeniorManager" eSuperTypes="#//EClass">
    <eAnnotations source="type=SeniorManagerRole"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaulAlter" eSuperTypes="#//EClass">
    <eAnnotations source="type=Actor@3"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performs" upperBound="-1"
        eType="#//AssesssingClaim123">
      <eAnnotations source="type=performs@3"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectLeader" eSuperTypes="#//EClass">
    <eAnnotations source="type=ProjectLeaderRole"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssesssingClaim123" eSuperTypes="#//EClass">
    <eAnnotations source="type=AssessClaimTask"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beginDate" upperBound="-2"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="value">
        <details key="value" value="01-Jan-19"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" upperBound="-2"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="value">
        <details key="value" value="02-Jan-19"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produces" upperBound="-1"
        eType="#//ClaimPayment4">
      <eAnnotations source="type=produces"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JackMiller">
    <eAnnotations source="type=IActor@2"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__relationNames" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__potency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__parentNodes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__isAbstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supID" upperBound="-2"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="potency">
        <details key="potencyStart" value="1"/>
        <details key="potencyEnd" value="1"/>
        <details key="potencyDepth" value="1"/>
      </eAnnotations>
      <eAnnotations source="value">
        <details key="value" value="0004"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supervises" upperBound="-1"
        eType="#//ClaimPayment4">
      <eAnnotations source="type=supervisorActor@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimPayment4">
    <eAnnotations source="type=ClaimPaymentDecisionArtifact"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__relationNames" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__potency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__parentNodes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__isAbstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
